In [1]:
import pandas as pd
import nltk
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/diegocristobal/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/diegocristobal/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/diegocristobal/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/diegocristobal/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [2]:
!pip install nltk

Requirement already satisfied: nltk in /Users/diegocristobal/.pyenv/versions/3.8.12/envs/book_recommender/lib/python3.8/site-packages (3.7)
Requirement already satisfied: regex>=2021.8.3 in /Users/diegocristobal/.pyenv/versions/3.8.12/envs/book_recommender/lib/python3.8/site-packages (from nltk) (2022.8.17)
Requirement already satisfied: click in /Users/diegocristobal/.pyenv/versions/3.8.12/envs/book_recommender/lib/python3.8/site-packages (from nltk) (8.1.3)
Requirement already satisfied: tqdm in /Users/diegocristobal/.pyenv/versions/3.8.12/envs/book_recommender/lib/python3.8/site-packages (from nltk) (4.64.0)
Requirement already satisfied: joblib in /Users/diegocristobal/.pyenv/versions/3.8.12/envs/book_recommender/lib/python3.8/site-packages (from nltk) (1.1.0)

In [3]:
df=pd.read_csv("/Users/diegocristobal/code/dieg9906/book_recommender/book_recommender/data/books_withdesc.csv")

In [4]:
df.head(5)

,Unnamed: 0,book_id,title,ratings,url,cover_img,isbn,authors,description
0,0,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,0743294297,"[{'author_id': '9212', 'role': ''}]",Addie Downs and Valerie Adler were eight when ...
1,1,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,0922915113,"[{'author_id': '2983296', 'role': ''}, {'autho...","Wisdom, humor, and dark observations by the fo..."
2,2,6066814,"Crowner Royal (Crowner John Mystery, #13)",186,https://www.goodreads.com/book/show/6066814-cr...,https://images.gr-assets.com/books/1328724803m...,184737297X,"[{'author_id': '37778', 'role': ''}]","London, 1196. At the command of Richard the Li..."
3,3,33394837,The House of Memory (Pluto's Snitch #2),269,https://www.goodreads.com/book/show/33394837-t...,https://images.gr-assets.com/books/1493114742m...,NaN,"[{'author_id': '242185', 'role': ''}]",NaN
4,4,89375,90 Minutes in Heaven: A True Story of Death an...,68157,https://www.goodreads.com/book/show/89375.90_M...,https://s.gr-assets.com/assets/nophoto/book/11...,0800759494,"[{'author_id': '39054', 'role': ''}, {'author_...",As he is driving home from a minister's confer...

In [10]:
df["title"].head(5)

0                                 Best Friends Forever
1                                 The Devil's Notebook
2            Crowner Royal (Crowner John Mystery, #13)
4    90 Minutes in Heaven: A True Story of Death an...
5                                               Heaven
Name: title, dtype: object

# Minimize Characters for Search Engine

We replace any characters that don't fall in ^a-zA-Z0-9

In [11]:
df=df.dropna()

In [12]:
df["mod_title"] = df["title"].str.replace("[^a-zA-Z0-9 ]", "", regex=True)

In [13]:
df["mod_title"]

0                                      Best Friends Forever
1                                       The Devils Notebook
2                     Crowner Royal Crowner John Mystery 13
4         90 Minutes in Heaven A True Story of Death and...
5                                                    Heaven
                                ...
381176                                          The Mad Man
381177    The Lonely Soldier The Private War of Women Se...
381178    Harry Potter and the Philosophers Stone Harry ...
381182                       The Spanish Dukes Virgin Bride
381188                The Brazilian Bosss Innocent Mistress
Name: mod_title, Length: 233336, dtype: object

In [14]:
df["mod_title"] = df["mod_title"].str.replace("\s+", " ", regex=True)

In [15]:
df["mod_title"]

0                                      Best Friends Forever
1                                       The Devils Notebook
2                     Crowner Royal Crowner John Mystery 13
4         90 Minutes in Heaven A True Story of Death and...
5                                                    Heaven
                                ...
381176                                          The Mad Man
381177    The Lonely Soldier The Private War of Women Se...
381178    Harry Potter and the Philosophers Stone Harry ...
381182                       The Spanish Dukes Virgin Bride
381188                The Brazilian Bosss Innocent Mistress
Name: mod_title, Length: 233336, dtype: object

In [16]:
df["mod_title"]=df["mod_title"].str.lower()

In [17]:
df["mod_title"]

0                                      best friends forever
1                                       the devils notebook
2                     crowner royal crowner john mystery 13
4         90 minutes in heaven a true story of death and...
5                                                    heaven
                                ...
381176                                          the mad man
381177    the lonely soldier the private war of women se...
381178    harry potter and the philosophers stone harry ...
381182                       the spanish dukes virgin bride
381188                the brazilian bosss innocent mistress
Name: mod_title, Length: 233336, dtype: object

In [18]:
df = df[df["mod_title"].str.len() > 0]

In [19]:
df["mod_title"]

0                                      best friends forever
1                                       the devils notebook
2                     crowner royal crowner john mystery 13
4         90 minutes in heaven a true story of death and...
5                                                    heaven
                                ...
381176                                          the mad man
381177    the lonely soldier the private war of women se...
381178    harry potter and the philosophers stone harry ...
381182                       the spanish dukes virgin bride
381188                the brazilian bosss innocent mistress
Name: mod_title, Length: 232967, dtype: object

In [ ]:
df.to_json("books_titles.json")

In [ ]:
df["mod_title"]

In [20]:
df

,Unnamed: 0,book_id,title,ratings,url,cover_img,isbn,authors,description,mod_title
0,0,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,0743294297,"[{'author_id': '9212', 'role': ''}]",Addie Downs and Valerie Adler were eight when ...,best friends forever
1,1,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,0922915113,"[{'author_id': '2983296', 'role': ''}, {'autho...","Wisdom, humor, and dark observations by the fo...",the devils notebook
2,2,6066814,"Crowner Royal (Crowner John Mystery, #13)",186,https://www.goodreads.com/book/show/6066814-cr...,https://images.gr-assets.com/books/1328724803m...,184737297X,"[{'author_id': '37778', 'role': ''}]","London, 1196. At the command of Richard the Li...",crowner royal crowner john mystery 13
4,4,89375,90 Minutes in Heaven: A True Story of Death an...,68157,https://www.goodreads.com/book/show/89375.90_M...,https://s.gr-assets.com/assets/nophoto/book/11...,0800759494,"[{'author_id': '39054', 'role': ''}, {'author_...",As he is driving home from a minister's confer...,90 minutes in heaven a true story of death and...
5,5,89376,Heaven,7345,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,0842379428,"[{'author_id': '4862', 'role': ''}]",What is Heaven really going to be like? What w...,heaven
...,...,...,...,...,...,...,...,...,...,...
381176,381176,786182,The Mad Man,151,https://www.goodreads.com/book/show/786182.The...,https://s.gr-assets.com/assets/nophoto/book/11...,0966599845,"[{'author_id': '49111', 'role': ''}]","For his thesis, graduate student John Marr res...",the mad man
381177,381177,6093345,The Lonely Soldier: The Private War of Women S...,207,https://www.goodreads.com/book/show/6093345-th...,https://images.gr-assets.com/books/1320482184m...,0807061476,"[{'author_id': '99046', 'role': ''}]",The Lonely Soldier--the inspiration for the do...,the lonely soldier the private war of women se...
381178,381178,1885731,Harry Potter and the Philosopher's Stone (Harr...,770,https://www.goodreads.com/book/show/1885731.Ha...,https://images.gr-assets.com/books/1387739847m...,0747549559,"[{'author_id': '1077326', 'role': ''}]",Harry Potter thinks he is an ordinary boy - un...,harry potter and the philosophers stone harry ...
381182,381182,2200344,The Spanish Duke's Virgin Bride,223,https://www.goodreads.com/book/show/2200344.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126794,"[{'author_id': '621880', 'role': ''}]","Revenge, passion and an arranged marriage...Du...",the spanish dukes virgin bride
381188,381188,1370179,The Brazilian Boss's Innocent Mistress,240,https://www.goodreads.com/book/show/1370179.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126646,"[{'author_id': '45898', 'role': ''}]",Deep in the Brazilian rainforest lies a rich a...,the brazilian bosss innocent mistress

# Description Preprocesing

In [21]:
df["mod_desc"] = df["description"].str.lower()

In [22]:
df["mod_desc"]  = df["mod_desc"].str.replace("[^a-zA-Z0-9 ]", "", regex=True)

In [23]:
df["mod_desc"]

0         addie downs and valerie adler were eight when ...
1         wisdom humor and dark observations by the foun...
2         london 1196 at the command of richard the lion...
4         as he is driving home from a ministers confere...
5         what is heaven really going to be like what wi...
                                ...
381176    for his thesis graduate student john marr rese...
381177    the lonely soldierthe inspiration for the docu...
381178    harry potter thinks he is an ordinary boy  unt...
381182    revenge passion and an arranged marriageduke j...
381188    deep in the brazilian rainforest lies a rich a...
Name: mod_desc, Length: 232967, dtype: object

In [24]:

def cleaning(sentence):
    
    # Basic cleaning
    sentence = sentence.strip() ## remove whitespaces
    sentence = sentence.lower() ## lowercase 
    sentence = ''.join(char for char in sentence if not char.isdigit()) ## remove numbers
    
    # Advanced cleaning
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '') ## remove punctuation
    
    tokenized_sentence = word_tokenize(sentence) ## tokenize 
    stop_words = set(stopwords.words('english')) ## define stopwords
    
    tokenized_sentence_cleaned = [ ## remove stopwords
        w for w in tokenized_sentence if not w in stop_words
    ]
    lemmatized = [
        WordNetLemmatizer().lemmatize(word, pos = "v") 
        for word in tokenized_sentence_cleaned
    ]
    
    cleaned_sentence = ' '.join(word for word in lemmatized)
    
    return cleaned_sentence

In [25]:
df["mod_desc"]=df["description"].apply(cleaning)

In [26]:
df

,Unnamed: 0,book_id,title,ratings,url,cover_img,isbn,authors,description,mod_title,mod_desc
0,0,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,0743294297,"[{'author_id': '9212', 'role': ''}]",Addie Downs and Valerie Adler were eight when ...,best friends forever,addie down valerie adler eight first meet deci...
1,1,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,0922915113,"[{'author_id': '2983296', 'role': ''}, {'autho...","Wisdom, humor, and dark observations by the fo...",the devils notebook,wisdom humor dark observations founder church ...
2,2,6066814,"Crowner Royal (Crowner John Mystery, #13)",186,https://www.goodreads.com/book/show/6066814-cr...,https://images.gr-assets.com/books/1328724803m...,184737297X,"[{'author_id': '37778', 'role': ''}]","London, 1196. At the command of Richard the Li...",crowner royal crowner john mystery 13,london command richard lionheart sir john de w...
4,4,89375,90 Minutes in Heaven: A True Story of Death an...,68157,https://www.goodreads.com/book/show/89375.90_M...,https://s.gr-assets.com/assets/nophoto/book/11...,0800759494,"[{'author_id': '39054', 'role': ''}, {'author_...",As he is driving home from a minister's confer...,90 minutes in heaven a true story of death and...,drive home minister conference baptist ministe...
5,5,89376,Heaven,7345,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,0842379428,"[{'author_id': '4862', 'role': ''}]",What is Heaven really going to be like? What w...,heaven,heaven really go like look like wont heaven ge...
...,...,...,...,...,...,...,...,...,...,...,...
381176,381176,786182,The Mad Man,151,https://www.goodreads.com/book/show/786182.The...,https://s.gr-assets.com/assets/nophoto/book/11...,0966599845,"[{'author_id': '49111', 'role': ''}]","For his thesis, graduate student John Marr res...",the mad man,thesis graduate student john marr research lif...
381177,381177,6093345,The Lonely Soldier: The Private War of Women S...,207,https://www.goodreads.com/book/show/6093345-th...,https://images.gr-assets.com/books/1320482184m...,0807061476,"[{'author_id': '99046', 'role': ''}]",The Lonely Soldier--the inspiration for the do...,the lonely soldier the private war of women se...,lonely soldierthe inspiration documentary invi...
381178,381178,1885731,Harry Potter and the Philosopher's Stone (Harr...,770,https://www.goodreads.com/book/show/1885731.Ha...,https://images.gr-assets.com/books/1387739847m...,0747549559,"[{'author_id': '1077326', 'role': ''}]",Harry Potter thinks he is an ordinary boy - un...,harry potter and the philosophers stone harry ...,harry potter think ordinary boy rescue owl tak...
381182,381182,2200344,The Spanish Duke's Virgin Bride,223,https://www.goodreads.com/book/show/2200344.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126794,"[{'author_id': '621880', 'role': ''}]","Revenge, passion and an arranged marriage...Du...",the spanish dukes virgin bride,revenge passion arrange marriageduke javier he...
381188,381188,1370179,The Brazilian Boss's Innocent Mistress,240,https://www.goodreads.com/book/show/1370179.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126646,"[{'author_id': '45898', 'role': ''}]",Deep in the Brazilian rainforest lies a rich a...,the brazilian bosss innocent mistress,deep brazilian rainforest lie rich reclusive b...

In [31]:
from nltk.corpus import words
nltk.download('words')
import numpy as np
# Remove non english words
en_words = set(words.words())
df["mod_desc"] = df["mod_desc"].apply(lambda x: " ".join(w for w in x.split()\
                            if w in en_words))
df["mod_desc"].replace('', np.nan, inplace=True)
df.dropna(subset=["mod_desc"], inplace=True)

[nltk_data] Downloading package words to
[nltk_data]     /Users/diegocristobal/nltk_data...
[nltk_data]   Package words is already up-to-date!

In [33]:
df

,Unnamed: 0,book_id,title,ratings,url,cover_img,isbn,authors,description,mod_title,mod_desc
0,0,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,0743294297,"[{'author_id': '9212', 'role': ''}]",Addie Downs and Valerie Adler were eight when ...,best friends forever,down eight first meet decide best forever wake...
1,1,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,0922915113,"[{'author_id': '2983296', 'role': ''}, {'autho...","Wisdom, humor, and dark observations by the fo...",the devils notebook,wisdom humor dark founder church satan ponder ...
2,2,6066814,"Crowner Royal (Crowner John Mystery, #13)",186,https://www.goodreads.com/book/show/6066814-cr...,https://images.gr-assets.com/books/1328724803m...,184737297X,"[{'author_id': '37778', 'role': ''}]","London, 1196. At the command of Richard the Li...",crowner royal crowner john mystery 13,command lionheart sir de leave beloved west co...
4,4,89375,90 Minutes in Heaven: A True Story of Death an...,68157,https://www.goodreads.com/book/show/89375.90_M...,https://s.gr-assets.com/assets/nophoto/book/11...,0800759494,"[{'author_id': '39054', 'role': ''}, {'author_...",As he is driving home from a minister's confer...,90 minutes in heaven a true story of death and...,drive home minister conference minister piper ...
5,5,89376,Heaven,7345,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,0842379428,"[{'author_id': '4862', 'role': ''}]",What is Heaven really going to be like? What w...,heaven,heaven really go like look like wont heaven ge...
...,...,...,...,...,...,...,...,...,...,...,...
381176,381176,786182,The Mad Man,151,https://www.goodreads.com/book/show/786182.The...,https://s.gr-assets.com/assets/nophoto/book/11...,0966599845,"[{'author_id': '49111', 'role': ''}]","For his thesis, graduate student John Marr res...",the mad man,thesis graduate student research life work bri...
381177,381177,6093345,The Lonely Soldier: The Private War of Women S...,207,https://www.goodreads.com/book/show/6093345-th...,https://images.gr-assets.com/books/1320482184m...,0807061476,"[{'author_id': '99046', 'role': ''}]",The Lonely Soldier--the inspiration for the do...,the lonely soldier the private war of women se...,lonely inspiration documentary invisible tell ...
381178,381178,1885731,Harry Potter and the Philosopher's Stone (Harr...,770,https://www.goodreads.com/book/show/1885731.Ha...,https://images.gr-assets.com/books/1387739847m...,0747549559,"[{'author_id': '1077326', 'role': ''}]",Harry Potter thinks he is an ordinary boy - un...,harry potter and the philosophers stone harry ...,harry potter think ordinary boy rescue owl tak...
381182,381182,2200344,The Spanish Duke's Virgin Bride,223,https://www.goodreads.com/book/show/2200344.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126794,"[{'author_id': '621880', 'role': ''}]","Revenge, passion and an arranged marriage...Du...",the spanish dukes virgin bride,revenge passion arrange need wife order inheri...
381188,381188,1370179,The Brazilian Boss's Innocent Mistress,240,https://www.goodreads.com/book/show/1370179.Th...,https://s.gr-assets.com/assets/nophoto/book/11...,0373126646,"[{'author_id': '45898', 'role': ''}]",Deep in the Brazilian rainforest lies a rich a...,the brazilian bosss innocent mistress,deep lie rich reclusive billionaire need luxur...

# Preprocessing Function

In [ ]:
def preprocessing_book_title(df):
    df=df.dropna()
    df["mod_title"] = df["title"].str.replace("[^a-zA-Z0-9 ]", "", regex=True)
    df["mod_title"] = df["mod_title"].str.replace("\s+", " ", regex=True)
    df["mod_title"]=df["mod_title"].str.lower()
    df = df[df["mod_title"].str.len() > 0]
    return df

In [ ]:
 def preprocessing_book_desc(df):
        df=df.dropna()
        df["mod_desc"] = df["description"].str.lower()
        df["mod_desc"]  = df["mod_desc"].str.replace("[^a-zA-Z0-9 ]", "", regex=True)
        df["mod_desc"]=df["description"].apply(cleaning)
        return df

In [ ]:
def cleaning(sentence):
    
    # Basic cleaning
    sentence = sentence.strip() ## remove whitespaces
    sentence = sentence.lower() ## lowercase 
    sentence = ''.join(char for char in sentence if not char.isdigit()) ## remove numbers
    
    # Advanced cleaning
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '') ## remove punctuation
    
    tokenized_sentence = word_tokenize(sentence) ## tokenize 
    stop_words = set(stopwords.words('english')) ## define stopwords
    
    tokenized_sentence_cleaned = [ ## remove stopwords
        w for w in tokenized_sentence if not w in stop_words
    ]
    lemmatized = [
        WordNetLemmatizer().lemmatize(word, pos = "v") 
        for word in tokenized_sentence_cleaned
    ]
    
    cleaned_sentence = ' '.join(word for word in lemmatized)
    
    return cleaned_sentence

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

tfidf = vectorizer.fit_transform(df["mod_title"])

In [35]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re

def make_clickable(val):
    return '<a target="_blank" href="{}">Goodreads</a>'.format(val, val)

def show_image(val):
    return '<a href="{}"><img src="{}" width=50></img></a>'.format(val, val)

def search(query,vectorizer):
    processed = re.sub("[^a-zA-Z0-9 ]", "", query.lower())
    query_vec = vectorizer.transform([query])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -10)[-10:]
    results = titles.iloc[indices]
    results = results.sort_values("ratings", ascending=False)
    
    return results.head(5).style.format({'url': make_clickable, 'cover_image': show_image})