In [1]:
import pandas as pd
import numpy as np
from google.cloud import bigquery

In [2]:
liked_books = [4408, 31147619, 29983711, 9401317, 9317691, 8153988, 20494944]

In [3]:
def find_users(liked_books : list):

    client = bigquery.Client()

    query = f'''
    SELECT DISTINCT(user_id) FROM `lewagon-bootcamp-356013.book_recommender.interactions2`
    WHERE book_id IN {tuple(liked_books)}
    AND rating >= 4
    '''

    overlap_users = client.query(query).to_dataframe()['user_id'].tolist()
    return overlap_users

In [4]:
def books_users(overlap_users):
    client = bigquery.Client()
    query=f'''
    SELECT user_id, book_id, rating FROM `lewagon-bootcamp-356013.book_recommender.interactions2`
    WHERE user_id IN {tuple(overlap_users)}
    '''
    book_recs = client.query(query).to_dataframe()
    return book_recs

In [5]:
%%time
overlap_users = find_users([4408, 31147619, 29983711, 9401317, 9317691, 8153988, 20494944])

CPU times: user 89 ms, sys: 18.5 ms, total: 108 ms
Wall time: 2.57 s

In [6]:
overlap_users

[312189,
 226957,
 23317,
 644686,
 395162,
 115044,
 428851,
 115504,
 95439,
 378430,
 298754,
 379226,
 6720,
 161156,
 395241,
 619923,
 325549,
 430660,
 416199,
 301400,
 285762,
 192627,
 470082,
 77955,
 323171,
 366903,
 11212,
 218199,
 348620,
 426783,
 338781,
 387089,
 398767,
 268062,
 427144,
 199488,
 699282,
 91569,
 298591,
 765062,
 50536,
 680773,
 95578,
 386688,
 683420,
 71545,
 130537,
 430898,
 34061,
 418691,
 72647,
 162501,
 267434,
 354195,
 220772,
 201861,
 357069,
 209927,
 167798,
 65923,
 18754,
 263621,
 351507,
 351082,
 370801,
 234991,
 299817,
 263739,
 701685,
 471343,
 39128,
 261926,
 391394,
 269319,
 270514,
 354931,
 211215,
 85762,
 707751,
 101390,
 139667,
 12557,
 159892,
 86051,
 334631,
 326471,
 86969,
 427059,
 192648,
 344911,
 310068,
 384324,
 242950,
 346712,
 73985,
 70283,
 183363,
 75556,
 436901,
 401994,
 90584,
 580184,
 189573,
 156223,
 374475,
 330159,
 107180,
 84211,
 167296,
 519237,
 92392,
 414260,
 123702,
 847396,
 11056,
 298101,
 104296,
 44000,
 72466,
 41256,
 398361,
 245866,
 149825,
 720668,
 6641,
 6251,
 321908,
 182849,
 442280,
 259647,
 217078,
 330029,
 873216,
 388247,
 352198,
 228754,
 99009,
 252224,
 76311,
 24080,
 235250,
 498037,
 312192,
 412313,
 426551,
 465254,
 434561,
 147858,
 351200,
 208330,
 10484,
 197395,
 351113,
 40519,
 68761,
 435885,
 192844,
 238035,
 49546,
 302743,
 330170,
 354861,
 408907,
 35920,
 203590,
 751500,
 206966,
 734110,
 345648,
 288776,
 439274,
 278725,
 360266,
 283500,
 108690,
 190962,
 417005,
 139375,
 139452,
 110623,
 178020,
 387266,
 357228,
 219722,
 251745,
 18145,
 45728,
 767701,
 50125,
 121515,
 474901,
 13987,
 196106,
 198323,
 261583,
 438051,
 345104,
 359282,
 310453,
 16565,
 293731,
 161813,
 221956,
 266401,
 321221,
 361684,
 399989,
 244569,
 325232,
 303866,
 314219,
 286049,
 260277,
 23294,
 70898,
 15852,
 67795,
 202771,
 107525,
 142185,
 329159,
 91446,
 264635,
 707624,
 175783,
 8648,
 860889,
 164350,
 67956,
 305844,
 161926,
 258328,
 404631,
 249603,
 163434,
 169721,
 196469,
 24372,
 240729,
 334077,
 12235,
 585984,
 349970,
 376349,
 294320,
 519106,
 224715,
 19310,
 218285,
 316741,
 122936,
 401779,
 376149,
 438882,
 75160,
 406670,
 62929,
 351119,
 186776,
 56560,
 497819,
 15202,
 339774,
 279105,
 227747,
 426793,
 26496,
 271469,
 425817,
 155598,
 284137,
 19836,
 180654,
 425068,
 133613,
 50330,
 205681,
 4629,
 269889,
 149721,
 416962,
 11559,
 545504,
 298556,
 436804,
 426318,
 217410,
 185031,
 3681,
 111417,
 348999,
 174642,
 440384,
 380626,
 351894,
 366525,
 436588,
 559548,
 728182,
 37512,
 165030,
 101423,
 252734,
 410471,
 32114,
 169935,
 316702,
 389036,
 238176,
 84944,
 137303,
 200302,
 432932,
 95392,
 181662,
 58606,
 383179,
 85887,
 125022,
 55557,
 46982,
 391314,
 338754,
 256237,
 270882,
 43729,
 410906,
 354825,
 105587,
 85129,
 245689,
 319130,
 315160,
 266803,
 343733,
 425189,
 202223,
 1448,
 194054,
 109400,
 285209,
 236013,
 207327,
 228152,
 142583,
 373460,
 407051,
 422297,
 195236,
 192206,
 167198,
 152618,
 93000,
 140965,
 20510,
 375800,
 235788,
 309781,
 387199,
 216965,
 368524,
 786557,
 203257,
 22910,
 347349,
 858314,
 2354,
 427466,
 375739,
 148149,
 249715,
 113622,
 152679,
 431251,
 93458,
 381816,
 155530,
 386104,
 294325,
 115473,
 298202,
 120783,
 193530,
 328643,
 422427,
 159434,
 352347,
 343765,
 114394,
 239744,
 407035,
 32945,
 83222,
 16154,
 421540,
 3928,
 164137,
 433962,
 159859,
 245204,
 331798,
 415383,
 98021,
 193761,
 57928,
 85455,
 206249,
 854889,
 453587,
 615754,
 333194,
 850541,
 292583,
 356809,
 292148,
 285093,
 207685,
 85264,
 95674,
 253919,
 343346,
 372762,
 433071,
 686468,
 391944,
 316621,
 114290,
 460884,
 9959,
 385762,
 225459,
 20003,
 21538,
 284215,
 134110,
 36158,
 765483,
 16679,
 302660,
 136455,
 11396,
 179213,
 344128,
 441346,
 434212,
 220059,
 319887,
 243583,
 317043,
 7060,
 151632,
 98361,
 9500,
 55760,
 153437,
 409467,
 18847,
 425521,
 69055,
 428828,
 161789,
 229593,
 848543,
 330698,
 125354,
 195353,
 513324,
 205962,
 798208,
 371504,
 62008,
 250653,
 368003,
 259761,
 12202,
 307762,
 389507,
 158906,
 352054,
 369650,
 86241,
 28564,
 789297,
 239725,
 286587,
 405885,
 249328,
 785494,
 241688,
 332667,
 483537,
 278873,
 81947,
 73094,
 12363,
 411279,
 114860,
 118724,
 696543,
 430034,
 11775,
 719811,
 303273,
 69004,
 364373,
 372112,
 736100,
 306623,
 298294,
 15862,
 186532,
 772390,
 138252,
 429715,
 398312,
 428928,
 422593,
 311678,
 827474,
 243240,
 379579,
 248141,
 192123,
 221836,
 363687,
 423723,
 251166,
 354154,
 332392,
 264659,
 199892,
 69460,
 158135,
 670631,
 147112,
 7325,
 37291,
 427639,
 354319,
 352129,
 125326,
 173620,
 107163,
 194945,
 393378,
 22487,
 433993,
 353036,
 10847,
 63627,
 151118,
 318859,
 381428,
 44801,
 408331,
 114998,
 102395,
 258578,
 428301,
 226933,
 431121,
 120079,
 292290,
 315356,
 432016,
 357599,
 217110,
 349941,
 71757,
 440355,
 36428,
 124161,
 20014,
 778418,
 310670,
 664861,
 390156,
 159402,
 103850,
 314891,
 331360,
 373541,
 326999,
 121526,
 244575,
 297908,
 196386,
 323079,
 416890,
 558,
 376226,
 349879,
 439908,
 151240,
 290488,
 115949,
 156333,
 65372,
 318120,
 188566,
 396795,
 348725,
 126209,
 22214,
 125489,
 298786,
 85698,
 245165,
 203842,
 136894,
 33458,
 151670,
 613093,
 358078,
 299855,
 371117,
 298208,
 129656,
 425665,
 750915,
 389364,
 234767,
 238188,
 372136,
 378992,
 33826,
 1593,
 408044,
 356727,
 160320,
 417495,
 976,
 706343,
 207644,
 2029,
 9964,
 419179,
 404014,
 211282,
 424569,
 350992,
 79071,
 785738,
 422067,
 215270,
 408835,
 249128,
 410687,
 280248,
 109930,
 10365,
 389000,
 358840,
 191515,
 219422,
 406403,
 115833,
 262368,
 147951,
 69724,
 105602,
 347210,
 410321,
 140964,
 288072,
 403282,
 59269,
 438433,
 176013,
 199044,
 154573,
 209110,
 30482,
 835720,
 274841,
 335473,
 664296,
 299697,
 100931,
 384069,
 51092,
 267591,
 139061,
 334624,
 71952,
 13645,
 78719,
 177788,
 6640,
 439959,
 334578,
 232434,
 71066,
 266416,
 537267,
 421996,
 17950,
 132846,
 90867,
 46272,
 258430,
 153933,
 6954,
 292215,
 810879,
 18826,
 389620,
 299,
 157754,
 73024,
 375550,
 58601,
 685799,
 391592,
 195817,
 243054,
 395334,
 222084,
 254664,
 391456,
 493157,
 199628,
 67259,
 113004,
 331850,
 136944,
 130382,
 315250,
 265834,
 61697,
 91690,
 252686,
 179382,
 335452,
 56684,
 335151,
 349860,
 383184,
 402799,
 216302,
 458042,
 332918,
 544853,
 77201,
 288398,
 251291,
 867679,
 115539,
 18431,
 323987,
 246364,
 420058,
 110899,
 407832,
 358851,
 228928,
 333421,
 213109,
 274203,
 851144,
 436213,
 165745,
 346777,
 50781,
 323558,
 442173,
 355932,
 116314,
 267111,
 414998,
 145091,
 325523,
 150676,
 642976,
 218354,
 404190,
 438616,
 169159,
 352419,
 262475,
 356934,
 394165,
 391974,
 64844,
 262642,
 21638,
 205864,
 84888,
 284238,
 132523,
 350988,
 231144,
 153422,
 436126,
 754061,
 117801,
 257216,
 82116,
 30213,
 40690,
 173543,
 825998,
 332866,
 8117,
 549997,
 249383,
 169160,
 352948,
 339656,
 337065,
 261794,
 355135,
 307967,
 280264,
 245836,
 93775,
 104231,
 179509,
 349998,
 82536,
 214613,
 405622,
 9550,
 12506,
 80262,
 79179,
 349066,
 158174,
 291138,
 360922,
 363635,
 136826,
 336593,
 308806,
 597550,
 96012,
 440695,
 399312,
 54641,
 190523,
 738133,
 93682,
 409731,
 342954,
 29299,
 274168,
 437917,
 118997,
 441983,
 512283,
 740194,
 399070,
 269536,
 360801,
 437089,
 321674,
 3199,
 239695,
 185654,
 302819,
 377881,
 269342,
 123718,
 240591,
 352378,
 420578,
 218014,
 276818,
 430768,
 268078,
 273752,
 685166,
 610535,
 315534,
 421912,
 254466,
 917,
 199651,
 395053,
 90031,
 137677,
 188588,
 135974,
 374322,
 85270,
 408749,
 280055,
 40803,
 254485,
 430512,
 336584,
 351475,
 243926,
 764013,
 440507,
 4683,
 116372,
 421342,
 309930,
 381267,
 117725,
 825612,
 382108,
 375041,
 320956,
 257302,
 345156,
 392409,
 355094,
 525,
 166845,
 440810,
 427314,
 118721,
 106150,
 389331,
 291409,
 116343,
 198832,
 30424,
 352561,
 378446,
 253577,
 332590,
 75677,
 326540,
 203347,
 412125,
 140185,
 228053,
 201716,
 114678,
 214018,
 332298,
 438894,
 342356,
 348409,
 354629,
 187465,
 90638,
 359734,
 327723,
 263865,
 113176,
 129167,
 439462,
 325556,
 309061,
 209281,
 179162,
 477452,
 398883,
 263993,
 422258,
 407212,
 351626,
 12658,
 62162,
 103381,
 191447,
 331663,
 286392,
 238040,
 292047,
 395498,
 350003,
 373519,
 410533,
 599129,
 522129,
 50471,
 26448,
 292083,
 137899,
 250845,
 104934,
 120992,
 265708,
 88554,
 322703,
 417087,
 332130,
 154918,
 61702,
 316699,
 53393,
 374214,
 36127,
 226062,
 434486,
 856148,
 93121,
 321900,
 146149,
 384333,
 258170,
 38069,
 530267,
 161122,
 380112,
 ...]

In [7]:
%%time
recs = books_users(overlap_users)
recs

CPU times: user 797 ms, sys: 394 ms, total: 1.19 s
Wall time: 3.08 s

         user_id   book_id  rating
0         180248  25659647       0
1          17750  26114433       0
2         372762  15952899       0
3         305844  32495827       0
4         357069       961       0
...          ...       ...     ...
1530252    54641     32145       5
1530253    49765  18114449       5
1530254   349860    280410       5
1530255   239725  29875926       5
1530256   245165  29430012       5

[1530257 rows x 3 columns]

In [8]:
top_recs = recs["book_id"].value_counts().head(10)
top_recs

2767052     1092
29983711    1089
2657        1074
3           1048
4671        1028
18143977     977
38447        911
5470         907
5107         886
77203        886
Name: book_id, dtype: int64

In [9]:
index_top_recs = top_recs.index.values

In [10]:
books_titles = pd.read_json("books_titles.json")

In [11]:
books_titles[books_titles["book_id"].isin(index_top_recs)]

,book_id,title,ratings,url,cover_image,mod_title
71398,77203,The Kite Runner,1848782,https://www.goodreads.com/book/show/77203.The_...,https://images.gr-assets.com/books/1484565687m...,the kite runner
386663,2767052,"The Hunger Games (The Hunger Games, #1)",4899965,https://www.goodreads.com/book/show/2767052-th...,https://images.gr-assets.com/books/1447303603m...,the hunger games the hunger games 1
546297,5107,The Catcher in the Rye,2086945,https://www.goodreads.com/book/show/5107.The_C...,https://images.gr-assets.com/books/1398034300m...,the catcher in the rye
630937,4671,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby
838525,5470,1984,2023937,https://www.goodreads.com/book/show/5470.1984,https://images.gr-assets.com/books/1348990566m...,1984
1031472,38447,The Handmaid's Tale,648783,https://www.goodreads.com/book/show/38447.The_...,https://images.gr-assets.com/books/1498057733m...,the handmaids tale
1077226,2657,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird
1195873,18143977,All the Light We Cannot See,498685,https://www.goodreads.com/book/show/18143977-a...,https://images.gr-assets.com/books/1451445646m...,all the light we cannot see
1196415,3,Harry Potter and the Sorcerer's Stone (Harry P...,4765497,https://www.goodreads.com/book/show/3.Harry_Po...,https://images.gr-assets.com/books/1474154022m...,harry potter and the sorcerers stone harry pot...
1446134,29983711,Pachinko,8161,https://www.goodreads.com/book/show/29983711-p...,https://images.gr-assets.com/books/1462393298m...,pachinko

In [12]:
all_recs = recs['book_id'].value_counts().to_frame().reset_index()
all_recs.columns = ["book_id", "book_count"]
all_recs

         book_id  book_count
0        2767052        1092
1       29983711        1089
2           2657        1074
3              3        1048
4           4671        1028
...          ...         ...
364164    292677           1
364165    376546           1
364166      3816           1
364167    247861           1
364168  11151894           1

[364169 rows x 2 columns]

In [15]:
books_titles.head()

,book_id,title,ratings,url,cover_image,mod_title
0,1333909,Good Harbor,10,https://www.goodreads.com/book/show/1333909.Go...,https://s.gr-assets.com/assets/nophoto/book/11...,good harbor
1,7327624,"The Unschooled Wizard (Sun Wolf and Starhawk, ...",140,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,the unschooled wizard sun wolf and starhawk 12
2,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,best friends forever
3,287140,Runic Astrology: Starcraft and Timekeeping in ...,15,https://www.goodreads.com/book/show/287140.Run...,https://images.gr-assets.com/books/1413219371m...,runic astrology starcraft and timekeeping in t...
4,287141,The Aeneid for Boys and Girls,46,https://www.goodreads.com/book/show/287141.The...,https://s.gr-assets.com/assets/nophoto/book/11...,the aeneid for boys and girls

In [16]:
all_recs_titles = all_recs.merge(books_titles, how="inner", on="book_id")
all_recs_titles

,book_id,book_count,title,ratings,url,cover_image,mod_title
0,2767052,1092,"The Hunger Games (The Hunger Games, #1)",4899965,https://www.goodreads.com/book/show/2767052-th...,https://images.gr-assets.com/books/1447303603m...,the hunger games the hunger games 1
1,29983711,1089,Pachinko,8161,https://www.goodreads.com/book/show/29983711-p...,https://images.gr-assets.com/books/1462393298m...,pachinko
2,2657,1074,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird
3,3,1048,Harry Potter and the Sorcerer's Stone (Harry P...,4765497,https://www.goodreads.com/book/show/3.Harry_Po...,https://images.gr-assets.com/books/1474154022m...,harry potter and the sorcerers stone harry pot...
4,4671,1028,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby
...,...,...,...,...,...,...,...
351973,292677,1,"The Teeth of the Gale (Felix Brooke, #3)",128,https://www.goodreads.com/book/show/292677.The...,https://images.gr-assets.com/books/1328876095m...,the teeth of the gale felix brooke 3
351974,376546,1,"Dark Journey (Star Wars: The New Jedi Order, #10)",277,https://www.goodreads.com/book/show/376546.Dar...,https://images.gr-assets.com/books/1327942667m...,dark journey star wars the new jedi order 10
351975,3816,1,A Little Original Sin: The Life and Work of Ja...,147,https://www.goodreads.com/book/show/3816.A_Lit...,https://s.gr-assets.com/assets/nophoto/book/11...,a little original sin the life and work of jan...
351976,247861,1,"Things Kept, Things Left Behind",92,https://www.goodreads.com/book/show/247861.Thi...,https://images.gr-assets.com/books/1328863823m...,things kept things left behind
351977,11151894,1,Figuring Out Fibromyalgia: Current Science and...,53,https://www.goodreads.com/book/show/11151894-f...,https://s.gr-assets.com/assets/nophoto/book/11...,figuring out fibromyalgia current science and ...

In [17]:
all_recs_titles["score"] = all_recs_titles["book_count"] * (all_recs_titles["book_count"] / all_recs_titles["ratings"])

In [18]:
all_recs_titles.sort_values("score", ascending=False).head(10)

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
1,29983711,1089,Pachinko,8161,https://www.goodreads.com/book/show/29983711-p...,https://images.gr-assets.com/books/1462393298m...,pachinko,145.315648
7134,35069544,29,This Will Be My Undoing: Living at the Interse...,8,https://www.goodreads.com/book/show/35069544-t...,https://images.gr-assets.com/books/1502099764m...,this will be my undoing living at the intersec...,105.125000
14872,29749094,15,"Superman (DC Icons, #4)",7,https://www.goodreads.com/book/show/29749094-s...,https://s.gr-assets.com/assets/nophoto/book/11...,superman dc icons 4,32.142857
238,4408,327,East of Eden,3447,https://www.goodreads.com/book/show/4408.East_...,https://images.gr-assets.com/books/1323882457m...,east of eden,31.020888
724,9317691,175,The Name of the Wind (The Kingkiller Chronicle...,1043,https://www.goodreads.com/book/show/9317691-th...,https://images.gr-assets.com/books/1360558233m...,the name of the wind the kingkiller chronicle 1,29.362416
236,32920226,328,"Sing, Unburied, Sing",4592,https://www.goodreads.com/book/show/32920226-s...,https://images.gr-assets.com/books/1499340866m...,sing unburied sing,23.428571
12747,36301023,17,"My Plain Jane (The Lady Janies, #2)",13,https://www.goodreads.com/book/show/36301023-m...,https://images.gr-assets.com/books/1507936746m...,my plain jane the lady janies 2,22.230769
13174,26857046,17,The Invisible Life of Addie La Rue,13,https://www.goodreads.com/book/show/26857046-t...,https://s.gr-assets.com/assets/nophoto/book/11...,the invisible life of addie la rue,22.230769
15410,35430702,14,The Lady's Guide to Petticoats and Piracy,9,https://www.goodreads.com/book/show/35430702-t...,https://s.gr-assets.com/assets/nophoto/book/11...,the ladys guide to petticoats and piracy,21.777778
215,30753987,342,The Leavers,5602,https://www.goodreads.com/book/show/30753987-t...,https://images.gr-assets.com/books/1489158974m...,the leavers,20.878972

In [23]:
all_recs_titles.sort_values("score", ascending=False).head(10).to_json()

'{"book_id":{"1":29983711,"7134":35069544,"14872":29749094,"238":4408,"724":9317691,"236":32920226,"12747":36301023,"13174":26857046,"15410":35430702,"215":30753987},"book_count":{"1":1089,"7134":29,"14872":15,"238":327,"724":175,"236":328,"12747":17,"13174":17,"15410":14,"215":342},"title":{"1":"Pachinko","7134":"This Will Be My Undoing: Living at the Intersection of Black, Female, and Feminist in (White) America","14872":"Superman (DC Icons, #4)","238":"East of Eden","724":"The Name of the Wind (The Kingkiller Chronicle, #1)","236":"Sing, Unburied, Sing","12747":"My Plain Jane (The Lady Janies, #2)","13174":"The Invisible Life of Addie La Rue","15410":"The Lady\'s Guide to Petticoats and Piracy","215":"The Leavers"},"ratings":{"1":8161,"7134":8,"14872":7,"238":3447,"724":1043,"236":4592,"12747":13,"13174":13,"15410":9,"215":5602},"url":{"1":"https:\\/\\/www.goodreads.com\\/book\\/show\\/29983711-pachinko","7134":"https:\\/\\/www.goodreads.com\\/book\\/show\\/35069544-this-will-be-my-undoing","14872":"https:\\/\\/www.goodreads.com\\/book\\/show\\/29749094-superman","238":"https:\\/\\/www.goodreads.com\\/book\\/show\\/4408.East_of_Eden","724":"https:\\/\\/www.goodreads.com\\/book\\/show\\/9317691-the-name-of-the-wind","236":"https:\\/\\/www.goodreads.com\\/book\\/show\\/32920226-sing-unburied-sing","12747":"https:\\/\\/www.goodreads.com\\/book\\/show\\/36301023-my-plain-jane","13174":"https:\\/\\/www.goodreads.com\\/book\\/show\\/26857046-the-invisible-life-of-addie-la-rue","15410":"https:\\/\\/www.goodreads.com\\/book\\/show\\/35430702-the-lady-s-guide-to-petticoats-and-piracy","215":"https:\\/\\/www.goodreads.com\\/book\\/show\\/30753987-the-leavers"},"cover_image":{"1":"https:\\/\\/images.gr-assets.com\\/books\\/1462393298m\\/29983711.jpg","7134":"https:\\/\\/images.gr-assets.com\\/books\\/1502099764m\\/35069544.jpg","14872":"https:\\/\\/s.gr-assets.com\\/assets\\/nophoto\\/book\\/111x148-bcc042a9c91a29c1d680899eff700a03.png","238":"https:\\/\\/images.gr-assets.com\\/books\\/1323882457m\\/4408.jpg","724":"https:\\/\\/images.gr-assets.com\\/books\\/1360558233m\\/9317691.jpg","236":"https:\\/\\/images.gr-assets.com\\/books\\/1499340866m\\/32920226.jpg","12747":"https:\\/\\/images.gr-assets.com\\/books\\/1507936746m\\/36301023.jpg","13174":"https:\\/\\/s.gr-assets.com\\/assets\\/nophoto\\/book\\/111x148-bcc042a9c91a29c1d680899eff700a03.png","15410":"https:\\/\\/s.gr-assets.com\\/assets\\/nophoto\\/book\\/111x148-bcc042a9c91a29c1d680899eff700a03.png","215":"https:\\/\\/images.gr-assets.com\\/books\\/1489158974m\\/30753987.jpg"},"mod_title":{"1":"pachinko","7134":"this will be my undoing living at the intersection of black female and feminist in white america","14872":"superman dc icons 4","238":"east of eden","724":"the name of the wind the kingkiller chronicle 1","236":"sing unburied sing","12747":"my plain jane the lady janies 2","13174":"the invisible life of addie la rue","15410":"the ladys guide to petticoats and piracy","215":"the leavers"},"score":{"1":145.3156475922,"7134":105.125,"14872":32.1428571429,"238":31.0208877285,"724":29.3624161074,"236":23.4285714286,"12747":22.2307692308,"13174":22.2307692308,"15410":21.7777777778,"215":20.8789717958}}'

In [19]:
popular_recs = all_recs_titles[all_recs_titles["book_count"] > 200].sort_values("score", ascending=False)

In [20]:
popular_recs.head(10)

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
1,29983711,1089,Pachinko,8161,https://www.goodreads.com/book/show/29983711-p...,https://images.gr-assets.com/books/1462393298m...,pachinko,145.315648
238,4408,327,East of Eden,3447,https://www.goodreads.com/book/show/4408.East_...,https://images.gr-assets.com/books/1323882457m...,east of eden,31.020888
236,32920226,328,"Sing, Unburied, Sing",4592,https://www.goodreads.com/book/show/32920226-s...,https://images.gr-assets.com/books/1499340866m...,sing unburied sing,23.428571
215,30753987,342,The Leavers,5602,https://www.goodreads.com/book/show/30753987-t...,https://images.gr-assets.com/books/1489158974m...,the leavers,20.878972
249,8153988,322,"The Eye of the World (Wheel of Time, #1)",5740,https://www.goodreads.com/book/show/8153988-th...,https://images.gr-assets.com/books/1465920672m...,the eye of the world wheel of time 1,18.063415
438,33253215,236,The Heart's Invisible Furies,3629,https://www.goodreads.com/book/show/33253215-t...,https://images.gr-assets.com/books/1490803456m...,the hearts invisible furies,15.347479
71,30688435,533,Exit West,21378,https://www.goodreads.com/book/show/30688435-e...,https://images.gr-assets.com/books/1477324680m...,exit west,13.288848
250,32283423,321,American War,7776,https://www.goodreads.com/book/show/32283423-a...,https://images.gr-assets.com/books/1481494946m...,american war,13.251157
228,26025588,335,Behold the Dreamers,8793,https://www.goodreads.com/book/show/26025588-b...,https://images.gr-assets.com/books/1439643293m...,behold the dreamers,12.762993
344,17912498,266,The Queen of the Night,6115,https://www.goodreads.com/book/show/17912498-t...,https://images.gr-assets.com/books/1460425080m...,the queen of the night,11.570891

In [21]:
popular_recs[~popular_recs["book_id"].isin(liked_books)].head(10)

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
236,32920226,328,"Sing, Unburied, Sing",4592,https://www.goodreads.com/book/show/32920226-s...,https://images.gr-assets.com/books/1499340866m...,sing unburied sing,23.428571
215,30753987,342,The Leavers,5602,https://www.goodreads.com/book/show/30753987-t...,https://images.gr-assets.com/books/1489158974m...,the leavers,20.878972
438,33253215,236,The Heart's Invisible Furies,3629,https://www.goodreads.com/book/show/33253215-t...,https://images.gr-assets.com/books/1490803456m...,the hearts invisible furies,15.347479
71,30688435,533,Exit West,21378,https://www.goodreads.com/book/show/30688435-e...,https://images.gr-assets.com/books/1477324680m...,exit west,13.288848
250,32283423,321,American War,7776,https://www.goodreads.com/book/show/32283423-a...,https://images.gr-assets.com/books/1481494946m...,american war,13.251157
228,26025588,335,Behold the Dreamers,8793,https://www.goodreads.com/book/show/26025588-b...,https://images.gr-assets.com/books/1439643293m...,behold the dreamers,12.762993
344,17912498,266,The Queen of the Night,6115,https://www.goodreads.com/book/show/17912498-t...,https://images.gr-assets.com/books/1460425080m...,the queen of the night,11.570891
325,28114515,276,The Wangs vs. the World,7044,https://www.goodreads.com/book/show/28114515-t...,https://images.gr-assets.com/books/1451493647m...,the wangs vs the world,10.814310
108,34273236,459,Little Fires Everywhere,21135,https://www.goodreads.com/book/show/34273236-l...,https://images.gr-assets.com/books/1490351351m...,little fires everywhere,9.968346
104,28815371,467,The Mothers,22346,https://www.goodreads.com/book/show/28815371-t...,https://images.gr-assets.com/books/1460652458m...,the mothers,9.759644

In [ ]:
def get_recs(recs):
    all_recs = recs['book_id'].value_counts().to_frame().reset_index()
    all_recs.columns = ["book_id", "book_count"]
    all_recs_titles = all_recs.merge(books_titles, how="inner", on="book_id")
    all_recs_titles["score"] = all_recs_titles["book_count"] * (all_recs_titles["book_count"] / all_recs_titles["ratings"])
    all_recs_titles.sort_values("score", ascending=False).head(10)